macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  env:
    GRAALVM_VERSION: "21.0.2"
    GRAALVM_HOME: ${HOME}/graalvm-community-openjdk-21.0.2+13.1/Contents/Home
    TDN_PLATFORM: macos # used in release script
    TDN_ARCH: aarch64
    TDN_TEST_ENV: native
    GITHUB_TOKEN: ENCRYPTED[4a65d70fc1d0b3500658905e442f7fbcfdbec79151ab3c0b3946d9157d4a7fb8462d7282fab97c433f23b90e38687f56]
  script: |
    sudo script/install-clojure
    bash -x script/install-graalvm
    export PATH=$GRAALVM_HOME/bin:$PATH
    ls -lahrt $GRAALVM_HOME
    export JAVA_HOME=$GRAALVM_HOME
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version

    bash <(curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install) --dir $(pwd) --dev-build
    sudo mv bb /usr/local/bin
    bb script/compile.clj
    bb script/test.clj

    VERSION=$(cat resources/META-INF/borkdude/tools-deps-native/version.txt)
    archive="tools-deps-native-${VERSION}-${TDN_PLATFORM}-${TDN_ARCH:-amd64}.tar.gz"
    tar zcvf "$archive" tools-deps-native
    bb release-artifact "$archive" || true
  binaries_artifacts:
    path: "tools-deps-native-*.tar.gz"

