---

version: "v-{build}"

image: Visual Studio 2022

clone_folder: C:\projects\babashka

environment:
  GRAALVM_HOME: C:\projects\babashka\graalvm\graalvm-jdk-23+37.1
  BABASHKA_XMX: "-J-Xmx5g"
  JAVA_HOME: C:\projects\babashka\graalvm\graalvm-jdk-23+37.1

cache:
  - '%USERPROFILE%\.m2 -> deps.edn'
  - '%USERPROFILE%\.gitlibs -> deps.edn'
  - 'graalvm -> appveyor.yml'

install:
 - set PATH=%GRAALVM_HOME%\bin;%PATH%

clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive

build_script:
- cmd: >-

# set CLJ_KONDO_TEST_ENV=jvm

# call script/test.bat

# see https://github.com/quarkusio/quarkus/pull/7663

- cmd: >-

    powershell -Command "if (Test-Path('graalvm')) { return } else { (New-Object Net.WebClient).DownloadFile('https://download.oracle.com/graalvm/23/archive/graalvm-jdk-23_windows-x64_bin.zip', 'graalvm.zip') }"

    powershell -Command "if (Test-Path('graalvm')) { return } else { Expand-Archive graalvm.zip graalvm }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/babashka/babashka-dev-builds/releases/download/v1.0.169-SNAPSHOT/babashka-1.0.169-SNAPSHOT-windows-amd64.zip', 'bb.zip') }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { Expand-Archive bb.zip . }"

- cmd: >-
    where java
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
    where cl
    call bb script/compile.clj

- cmd: >-
    echo Creating zip archive

    set /P VERSION=< resources\META-INF\borkdude\tools-deps-native\version.txt

    set zip=tools-deps-native-%VERSION%-windows-amd64.zip

    jar -cMf %zip% tools-deps-native.exe

- cmd: >-
    where java

    call bb script/test.clj

artifacts:
- path: tools-deps-native-*-windows-amd64.zip
  name: tools-deps-native
