#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp tools-deps-native /tmp/release
VERSION=$(cat resources/META-INF/borkdude/tools-deps-native/version.txt)

cd /tmp/release

## release binary as zip archive

zip "tools-deps-native-$VERSION-$APP_PLATFORM-amd64.zip" tools-deps-native

## cleanup

rm tools-deps-native
