#!/bin/bash

set -eou pipefail

app_name=tools-deps-native
app_ns=borkdude.tdn.main

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

rm -rf classes
mkdir classes
clojure -e "(compile 'borkdude.tdn.main)"

"$GRAALVM_HOME/bin/native-image" \
    -cp "$(clojure -Spath):classes" \
    -H:Name=$app_name \
    -H:+ReportExceptionStackTraces \
    -H:ReflectionConfigurationFiles=reflection.json \
    -H:IncludeResources=clojure/tools/deps/deps.edn \
    -H:+JNI \
    "-H:Log=registerResource:" \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    --initialize-at-build-time \
    --report-unsupported-elements-at-runtime \
    --verbose \
    --no-fallback \
    --no-server \
    --initialize-at-run-time=com.jcraft.jsch.PortWatcher \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.ConnectorFactory \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.ConnectorFactory\$Default \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.PageantConnector \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.PageantConnector\$Kernel32 \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.PageantConnector\$User32 \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.SSHAgentConnector \
    --initialize-at-run-time=com.sun.jna.platform.win32.Kernel32 \
    --initialize-at-run-time=com.sun.jna.platform.win32.User32 \
    --initialize-at-run-time=org.eclipse.jgit.lib.RepositoryCache \
    --initialize-at-run-time=org.eclipse.jgit.lib.internal.WorkQueue \
    --initialize-at-run-time=org.eclipse.jgit.transport.AmazonS3 \
    --initialize-at-run-time=org.eclipse.jgit.transport.Transport \
    --initialize-at-run-time=org.eclipse.jgit.transport.TransportAmazonS3 \
    --allow-incomplete-classpath \
    "-J-Xmx3g" \
    ${app_ns}
