#!/bin/bash

set -eou pipefail

app_name=tools-deps-native
app_ns=borkdude.tdn.main

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

rm -rf classes
rm -rf tools-deps-native # should not be necessary, but just in case
mkdir classes
clojure -J-Dclojure.compiler.direct-linking=true -e "(compile 'borkdude.tdn.main)"

"$GRAALVM_HOME/bin/native-image" \
    -cp "$(clojure -Spath):classes" \
    -H:Name=$app_name \
    -H:+ReportExceptionStackTraces \
    -H:ReflectionConfigurationFiles=reflection.json \
    "-H:ResourceConfigurationFiles=resources.json" \
    -H:+JNI \
    "-H:Log=registerResource:" \
    "-H:EnableURLProtocols=http,https,jar" \
    "--enable-all-security-services" \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    --initialize-at-build-time \
    --report-unsupported-elements-at-runtime \
    --verbose \
    --no-fallback \
    --no-server \
    --initialize-at-run-time=com.jcraft.jsch.PortWatcher \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.ConnectorFactory \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.ConnectorFactory\$Default \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.PageantConnector \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.PageantConnector\$Kernel32 \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.PageantConnector\$User32 \
    --initialize-at-run-time=com.jcraft.jsch.agentproxy.connector.SSHAgentConnector \
    --initialize-at-run-time=com.sun.jna.platform.win32.Kernel32 \
    --initialize-at-run-time=com.sun.jna.platform.win32.User32 \
    --allow-incomplete-classpath \
    --trace-object-instantiation=java.lang.Thread \
    "-J-Xmx5g" \
    ${app_ns}
