#!/usr/bin/env bash

set -euo pipefail

INSTALL_DIR="${1:-$HOME}"

GRAALVM_VERSION="${GRAALVM_VERSION:-21.0.2}"

case "$TDN_PLATFORM" in
    macos)
        GRAALVM_PLATFORM="macos"
        ;;
    linux)
        GRAALVM_PLATFORM="linux"
        ;;
esac

case "${TDN_ARCH:-}" in
    aarch64)
        GRAALVM_ARCH="aarch64"
        ;;
    *)
        GRAALVM_ARCH="amd64"
        ;;
esac

GRAALVM_FILENAME="graalvm-community-jdk-${GRAALVM_VERSION}_${GRAALVM_PLATFORM}-${GRAALVM_ARCH}_bin.tar.gz"

pushd "$INSTALL_DIR" >/dev/null

if ! [ -d "graalvm-community-openjdk-21.0.2+13.1" ]; then
    echo "Downloading GraalVM $GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION on '$PWD'..."
    echo "https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-$GRAALVM_VERSION/$GRAALVM_FILENAME"
    curl -LO "https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-$GRAALVM_VERSION/$GRAALVM_FILENAME"
    ls -la
    tar xzvf "$GRAALVM_FILENAME"
    ls -la "graalvm-community-openjdk-21.0.2+13.1"
fi

popd >/dev/null
